name: Kora test action
description: Kora test action
inputs:
  test-task-name:
    description: 'Test task name'
    default: 'test'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew ${{ inputs.test-task-name }} --scan
      shell: bash
