name: Publish snapshot

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Retrieve the secret and decode it to a file
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: echo "$GPG_KEY" | base64 --decode > /tmp/secring.gpg

      - name: Retrieve the gradle.properties
        env:
          SIGN_OSSRH_GRADLE_PROPERTIES: ${{ secrets.SIGN_OSSRH_GRADLE_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle
          echo -en "$SIGN_OSSRH_GRADLE_PROPERTIES" > ~/.gradle/gradle.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish -Psigning.secretKeyRingFile=/tmp/secring.gpg
        env:
          REPO_URL: https://s01.oss.sonatype.org/content/repositories/snapshots
          REPO_USER: ${{ secrets.SONATYPE_USERNAME }}
          REPO_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
